  FROM mongo:16-alpine
  ENV MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
  ENV MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
  ENV MONGODB_SERVER: mongodb
  ENV BASICAUTH_USERNAME: admin
  ENV BASICAUTH_PASSWORD: admin123456

  EXPOSE 27017:27017
    