version: '3.8'

services: 
  frontend:
    image: izerekerie/frontend-image:latest
    stdin_open: true 
    tty: true 
    build: 
      context: electronic_frontend
      dockerfile: Dockerfile
    ports:
      - '80:3000'
  backend:
    image: izerekerie/online_electricity_backend_image:latest
    stdin_open: true
    tty: true 
    build: 
      context: izerekerie/online_electricity_backend_image:latest
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  db:
    image: izerekerie/db-image:latest
    stdin_open: true
    tty: true 
    build:
       context: .
       dockerfile: db.Dockerfile
    ports:
      - '5832:5832'
    volumes:
      - mongodb-data:/data/db
volumes:
  db: